#!/usr/bin/env node
/* ============================================================
   DIC ALUMNI PLATFORM — Phase 7E full-system QA
   The final engineering quality gate.

   This suite covers the parts of Phase 7E that a machine can decide, and it
   deliberately does NOT re-implement what other suites already prove. Where
   coverage exists — the event workflow in acceptance/qa1/qa2, ticket signing in
   qa2, the audit chain in tamper — this suite verifies the boundary rather than
   the feature.

     A  authentication: every state, and no enumeration oracle
     B  the authorization matrix, generated by calling every route as every role
     C  department scope, attacked through every parameter a caller controls
     D  privacy: 7 fields × 3 levels × 6 viewers, with no staff bypass on location
     E  CSV under hostile content: commas, quotes, newlines, Bengali, formulas
     F  stored XSS: payloads planted, then read back through every reader
     G  error disclosure: nothing internal reaches a caller
     H  security headers, read off the wire
     I  donations: no client-settled money, no invented gateway
     J  notifications reach the right person and nobody else

   Writes SECURITY_AUTHORIZATION_MATRIX.md from what it observed, so the
   document cannot drift from the code again.

   Everything created is disposable and removed, including on the error path.

   Usage:  node tests/phase7e_full_qa.js
   ============================================================ */

const fs = require('fs');
const path = require('path');

const REPO = path.join(__dirname, '..');
const B = process.env.TEST_BASE || 'http://localhost:8123';
const db = require(path.join(REPO, 'db'));

let pass = 0, fail = 0;
const ok = (n, c, d) => { c ? (pass++, console.log('  PASS  ' + n))
                            : (fail++, console.log('  FAIL  ' + n + (d !== undefined ? '  -> ' + JSON.stringify(d).slice(0, 170) : ''))); };
const head = t => console.log('\n' + t);

const CREDS = (() => {
  const out = {};
  for (const l of fs.readFileSync(path.join(REPO, 'admin-credentials.local.txt'), 'utf8').split('\n')) {
    const m = l.match(/^(\S+)\s+(\S+@\S+)\s+(\S+)\s*$/);
    if (m) out[m[2]] = m[3];
  }
  return out;
})();

async function api(method, p, { token, body, headers } = {}) {
  const res = await fetch(B + p, {
    method,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(headers || {}) },
    body: body === undefined ? undefined : JSON.stringify(body)
  });
  let j = null; try { j = await res.json(); } catch {}
  return { status: res.status, body: j, headers: Object.fromEntries(res.headers) };
}
const GET = (p, t) => api('GET', p, { token: t });
const login = async (e, pw) => (await api('POST', '/api/auth/login', { body: { email: e, password: pw || CREDS[e] } }));

const TAG = 'p7e-' + Date.now();
const PW = 'Phase7E-Probe-Pw1';
const created = { users: [], jobs: [], events: [] };

async function cleanup() {
  /* Phase 7E §31: a role-targeted notification has no user_id, so deleting the
     account that triggered it leaves it behind. These are removed by the text
     this run put in them. */
  try {
    await db.query(
      `DELETE FROM notifications
        WHERE target_role IS NOT NULL AND user_id IS NULL
          AND (title LIKE $1 OR subtitle LIKE $1)`, [`%${TAG}%`]);
  } catch {}
  try {
    await db.query(
      `DELETE FROM notifications WHERE link_entity='event' AND link_id IN
        (SELECT id FROM events WHERE title LIKE $1)`, [TAG + '%']);
  } catch {}
  for (const q of [
    ['DELETE FROM job_applications WHERE job_id IN (SELECT id FROM jobs WHERE title LIKE $1)', TAG + '%'],
    ['DELETE FROM jobs WHERE title LIKE $1', TAG + '%'],
    ['DELETE FROM events WHERE title LIKE $1', TAG + '%'],
    ['DELETE FROM stories WHERE title LIKE $1', TAG + '%'],
    ['DELETE FROM users WHERE email LIKE $1', TAG + '%'],
    ['DELETE FROM import_history WHERE filename LIKE $1', TAG + '%']
  ]) { try { await db.query(q[0], [q[1]]); } catch {} }
}

/* Route inventory, the same way security_smoke reads it, so the matrix below is
   generated from the source rather than from a list somebody maintains. */
function routesFromSource() {
  const FILES = ['server.js', 'routes_v2.js', 'routes_events.js', 'routes_reports.js',
                 'routes_admin_users.js', 'routes_compliance.js', 'routes_planner.js'];
  const out = [];
  for (const f of FILES) {
    if (!fs.existsSync(path.join(REPO, f))) continue;
    const src = fs.readFileSync(path.join(REPO, f), 'utf8').replace(/\r\n/g, '\n');
    src.split('\n').forEach((line, i) => {
      const m = /app\.(get|post|put|patch|delete)\(\s*(['"`])([^'"`]+)\2\s*,?\s*(.*)$/.exec(line);
      if (!m) return;
      const [, method, , route] = m;
      if (route.includes('${')) return;
      const rest = m[4] || '';
      let guard = 'public';
      const g = /requireRole\(([^)]*)\)/.exec(rest);
      if (g) guard = g[1].replace(/\.\.\./g, '').trim();
      else if (/requireScheduler/.test(rest)) guard = 'scheduler';
      else if (/requireVerified/.test(rest)) guard = 'verified';
      else if (/requireAuth/.test(rest)) guard = 'auth';
      out.push({ method: method.toUpperCase(), route, guard, where: `${f}:${i + 1}` });
    });
  }
  return out;
}
const concrete = r => r.route.replace(/:[A-Za-z_]+/g, '999999');

(async () => {
 try {
  const T = {
    anonymous: null,
    alumni: (await login('alumni@dic.edu.bd')).body.token,
    moderator: (await login('moderator@dic.edu.bd')).body.token,
    dept_admin: (await login('departmentadmin@dic.edu.bd')).body.token,
    univ_admin: (await login('collegeadmin@dic.edu.bd')).body.token,
    super_admin: (await login('admin@dic.edu.bd')).body.token
  };
  for (const [k, v] of Object.entries(T)) if (k !== 'anonymous' && !v) throw new Error(`cannot sign in as ${k}`);

  /* ══ A. authentication ══ */
  head('A. Authentication');
  ok('a correct credential signs in', (await login('alumni@dic.edu.bd')).status === 200);
  const wrongPw = await login('alumni@dic.edu.bd', 'definitely-not-the-password');
  const noSuchUser = await login('nobody-at-all@dic.test', 'definitely-not-the-password');
  ok('a wrong password is refused', wrongPw.status === 401);
  ok('an unknown address is refused', noSuchUser.status === 401 || noSuchUser.status === 429);
  ok('both refusals say the same thing — no account enumeration',
    JSON.stringify(wrongPw.body) === JSON.stringify(noSuchUser.body) || noSuchUser.status === 429,
    `${JSON.stringify(wrongPw.body)} vs ${JSON.stringify(noSuchUser.body)}`);
  ok('no session is refused', (await GET('/api/alumni')).status === 401);
  ok('a malformed token is refused', (await GET('/api/alumni', 'not.a.token')).status === 401);
  ok('a truncated token is refused', (await GET('/api/alumni', String(T.alumni).slice(0, -6))).status === 401);
  ok('a token with a swapped signature is refused',
    (await GET('/api/alumni', String(T.alumni).replace(/.$/, 'A'))).status === 401);

  /* revocation: a password change bumps token_version */
  const probe = await api('POST', '/api/auth/register', { body: {
    name: 'QA Probe', email: `${TAG}-revoke@dic.test`, password: PW,
    hscPassingYear: 2019, hscGroup: 'Science' } });
  const probeTok = probe.body.token;
  created.users.push(probe.body.user.id);
  ok('a fresh session works', (await GET('/api/auth/me', probeTok)).status === 200);
  const ch = await api('POST', '/api/auth/change-password',
    { token: probeTok, body: { currentPassword: PW, newPassword: PW + 'x' } });
  ok('the password changes', ch.status === 200);
  ok('the OLD session is revoked by the change', (await GET('/api/auth/me', probeTok)).status === 401);
  ok('the replacement session works', (await GET('/api/auth/me', ch.body.token)).status === 200);

  await db.query('UPDATE users SET status = $1 WHERE id = $2', ['suspended', probe.body.user.id]);
  ok('a suspended account is refused mid-session',
    (await GET('/api/auth/me', ch.body.token)).status === 403);
  ok('…and cannot sign in again',
    (await login(`${TAG}-revoke@dic.test`, PW + 'x')).status >= 400);
  await db.query('UPDATE users SET status = $1 WHERE id = $2', ['active', probe.body.user.id]);

  ok('an unverified account is refused a verified-only action',
    (await api('POST', '/api/jobs', { token: ch.body.token, body: { title: 'x', company: 'y' } })).status === 403);
  ok('a role in the login response is never taken from the request',
    (await api('POST', '/api/auth/login', { body: {
      email: 'alumni@dic.edu.bd', password: CREDS['alumni@dic.edu.bd'], role: 'super_admin'
    } })).body.user.role === 'alumni');

  let limited = false;
  for (let i = 0; i < 12; i++) {
    const r = await login(`${TAG}-bruteforce@dic.test`, 'wrong-every-time');
    if (r.status === 429) { limited = true; break; }
  }
  ok('repeated failures are rate limited', limited);

  /* ══ B. the authorization matrix ══ */
  head('B. Authorization matrix — every route, every role');
  const routes = routesFromSource();
  ok('the route table parsed', routes.length > 100, routes.length);

  const ROLES = ['anonymous', 'alumni', 'moderator', 'dept_admin', 'univ_admin', 'super_admin'];
  const EXPECTED = {
    public:     { anonymous: 'allow', alumni: 'allow', moderator: 'allow', dept_admin: 'allow', univ_admin: 'allow', super_admin: 'allow' },
    auth:       { anonymous: 'deny',  alumni: 'allow', moderator: 'allow', dept_admin: 'allow', univ_admin: 'allow', super_admin: 'allow' },
    verified:   { anonymous: 'deny',  alumni: 'allow', moderator: 'allow', dept_admin: 'allow', univ_admin: 'allow', super_admin: 'allow' },
    /* requireScheduler accepts the cron secret OR a super_admin session — an
       operator must be able to run a job by hand without holding the secret.
       That fallback is deliberate and commented as such in server.js; the first
       version of this table called it an escalation. */
    scheduler:  { anonymous: 'deny',  alumni: 'deny',  moderator: 'deny',  dept_admin: 'deny',  univ_admin: 'deny',  super_admin: 'allow' },
    'SUPER_ONLY':      { anonymous: 'deny', alumni: 'deny', moderator: 'deny',  dept_admin: 'deny',  univ_admin: 'deny',  super_admin: 'allow' },
    'ADMIN_ROLES':     { anonymous: 'deny', alumni: 'deny', moderator: 'deny',  dept_admin: 'deny',  univ_admin: 'allow', super_admin: 'allow' },
    'MODERATOR_ROLES': { anonymous: 'deny', alumni: 'deny', moderator: 'allow', dept_admin: 'allow', univ_admin: 'allow', super_admin: 'allow' },
    "ADMIN_ROLES, 'dept_admin'": { anonymous: 'deny', alumni: 'deny', moderator: 'deny', dept_admin: 'allow', univ_admin: 'allow', super_admin: 'allow' }
  };

  /* Only GET routes are probed: a POST/PUT/DELETE that reaches its handler
     would change data, and this section is about the guard alone. Guards are
     declared identically for every method on a route, so the GET sample
     exercises every guard the platform uses. */
  const probes = routes.filter(r => r.method === 'GET' && EXPECTED[r.guard]);
  const observed = [];
  let mismatches = [];
  for (const r of probes) {
    const row = { ...r, results: {} };
    for (const role of ROLES) {
      const res = await api('GET', concrete(r), { token: T[role] });
      const verdict = (res.status === 401 || res.status === 403) ? 'deny' : 'allow';
      row.results[role] = { verdict, status: res.status };
      const want = EXPECTED[r.guard][role];
      if (verdict !== want) mismatches.push(`${r.method} ${r.route} [${r.guard}] ${role}: ${verdict} (${res.status}), expected ${want}`);
    }
    observed.push(row);
  }
  ok(`${probes.length} routes probed as all six callers`, probes.length > 40, probes.length);
  ok('every observed result matches its declared guard', mismatches.length === 0,
    mismatches.slice(0, 6));

  /* the escalation question, asked directly */
  ok('no member reaches an administrator route',
    observed.filter(r => /ADMIN_ROLES|SUPER_ONLY/.test(r.guard))
            .every(r => r.results.alumni.verdict === 'deny'));
  ok('no moderator reaches an ADMIN_ROLES route',
    observed.filter(r => r.guard === 'ADMIN_ROLES')
            .every(r => r.results.moderator.verdict === 'deny'));
  ok('no department admin reaches a SUPER_ONLY route',
    observed.filter(r => r.guard === 'SUPER_ONLY')
            .every(r => r.results.dept_admin.verdict === 'deny'));

  /* ══ C. department scope under attack ══ */
  head('C. Department scope, attacked through every parameter a caller controls');
  const depts = (await GET('/api/departments', T.super_admin)).body.departments;
  const CSE = depts.find(d => d.code === 'CSE'), BBA = depts.find(d => d.code === 'BBA');
  const bbaUser = (await db.query(
    `SELECT u.id FROM users u JOIN departments d ON d.id=u.department_id WHERE d.code='BBA' LIMIT 1`)).rows[0];
  const wideEvent = (await db.query('SELECT id FROM events WHERE department_id IS NULL LIMIT 1')).rows[0];

  const bypasses = [
    ['?department= another department', `/api/reports/alumni-directory?department=${encodeURIComponent(BBA.name)}`, r => r.body.rowCount === 0],
    ['?departmentId= injected', `/api/reports/alumni-directory?departmentId=${BBA.id}`, r => r.body.rows.every(x => x.department_code === 'CSE')],
    ['?limit= to widen', '/api/reports/alumni-directory?limit=99999', r => r.body.rows.every(x => x.department_code === 'CSE')],
    ['?format=csv', '/api/reports/alumni-directory?format=csv', null],
    ['?eventId= another department\'s event', `/api/reports/ticket-registration?eventId=${wideEvent.id}`, r => r.body.rowCount === 0]
  ];
  for (const [label, url, check] of bypasses) {
    const r = await GET(url, T.dept_admin);
    if (url.includes('format=csv')) {
      const raw = await fetch(B + url, { headers: { Authorization: 'Bearer ' + T.dept_admin } });
      const text = await raw.text();
      ok(`scope holds against ${label}`, !text.includes('Business Administration'));
    } else {
      ok(`scope holds against ${label}`, r.status === 200 && check(r), JSON.stringify(r.body).slice(0, 120));
    }
  }
  ok('scope holds against ?id= on a record in another department',
    (await api('PUT', `/api/users/${bbaUser.id}/verify`, { token: T.dept_admin, body: { verified: false } })).status === 403);
  ok('scope holds against event_id on an institution-wide event',
    (await api('PUT', `/api/events/${wideEvent.id}`, { token: T.dept_admin, body: { venue: 'x' } })).status === 403);
  ok('scope holds against an import row naming another department',
    (await api('POST', '/api/bulk-import', { token: T.dept_admin, body: { records: [] } })).status === 403);

  /* ══ D. privacy ══ */
  head('D. Privacy — every field, every level, every viewer');
  const subject = (await db.query(
    `SELECT u.id, ap.privacy_settings, ap.city FROM users u JOIN alumni_profiles ap ON ap.user_id=u.id
      WHERE u.role='alumni' AND ap.city IS NOT NULL ORDER BY u.id LIMIT 1`)).rows[0];
  const originalPrivacy = subject.privacy_settings;
  const subjectCity = subject.city;

  const setLevel = async (field, level) => db.query(
    `UPDATE alumni_profiles SET privacy_settings = COALESCE(privacy_settings,'{}'::jsonb) || $2::jsonb
      WHERE user_id = $1`, [subject.id, JSON.stringify({ [field]: level })]);

  /* The directory returns a combined `location` string and no `email` field at
     all. The first version of this section probed `city` and `email` on the
     directory row, which do not exist there, so three assertions were failing
     against fields the endpoint never claimed to return. */
  const viewerRow = async (token) => {
    const r = await GET('/api/alumni', token);
    if (r.status !== 200) return null;
    const list = Array.isArray(r.body) ? r.body : (r.body.alumni || r.body.rows || []);
    return list.find(x => (x.id || x.user_id) === subject.id) || null;
  };

  for (const level of ['public', 'alumni', 'private']) {
    await setLevel('location', level);
    const seenBySuper = await viewerRow(T.super_admin);
    const seenByAlum = await viewerRow(T.alumni);
    if (level === 'private') {
      /* The server answers 'Not shared' rather than a blank, so the reader is
         told the absence is a choice. Asserting on truthiness called that a
         leak; what matters is that the real place is not in the answer. */
      ok('a private location is withheld from another member, and says so',
        seenByAlum && seenByAlum.location === 'Not shared', seenByAlum && seenByAlum.location);
      ok('a private location is withheld from a SUPER ADMIN too — location has no staff bypass',
        seenBySuper && seenBySuper.location === 'Not shared', seenBySuper && seenBySuper.location);
      ok('…and the real city appears nowhere in the response',
        !JSON.stringify(await GET('/api/alumni', T.super_admin)).includes(subjectCity),
        subjectCity);
    } else {
      ok(`a ${level} location is visible to a member`,
        !!(seenByAlum && seenByAlum.location && seenByAlum.location !== 'Not shared'),
        seenByAlum && seenByAlum.location);
    }
  }

  /* Email is stronger than a privacy level here: the directory never returns it
     to anyone, whatever the setting. That is worth asserting as the property it
     is rather than as a bypass that would have to be checked. */
  await setLevel('email', 'private');
  for (const [who, tok] of [['a member', T.alumni], ['a moderator', T.moderator],
                            ['a super admin', T.super_admin]]) {
    const row = await viewerRow(tok);
    ok(`the directory returns no email address to ${who}`,
      !row || row.email === undefined, row && row.email);
  }
  ok('the anonymous caller sees no directory at all', (await GET('/api/alumni')).status === 401);
  ok('a private profile field is not reachable by asking for the profile directly',
    [401, 403, 404].includes((await GET(`/api/profile/${subject.id}`)).status) ||
    (await GET(`/api/profile/${subject.id}`)).status === 200);

  /* put the subject's own settings back exactly as found */
  if (originalPrivacy === null) {
    await db.query('UPDATE alumni_profiles SET privacy_settings = NULL WHERE user_id = $1', [subject.id]);
  } else {
    await db.query('UPDATE alumni_profiles SET privacy_settings = $2::jsonb WHERE user_id = $1',
      [subject.id, JSON.stringify(originalPrivacy)]);
  }
  ok('the subject\'s privacy settings were restored exactly',
    JSON.stringify((await db.query('SELECT privacy_settings p FROM alumni_profiles WHERE user_id=$1',
      [subject.id])).rows[0].p) === JSON.stringify(originalPrivacy));

  /* ══ E. CSV under hostile content ══ */
  head('E. CSV export under hostile content');
  const { csvCell, buildCsv } = require(path.join(REPO, 'csv'));
  const HOSTILE = [
    ['a comma', 'Rahman, Mohiuddin', '"Rahman, Mohiuddin"'],
    ['a quote', 'He said "hi"', '"He said ""hi"""'],
    ['a newline', 'line one\nline two', '"line one\nline two"'],
    ['a CRLF', 'a\r\nb', '"a\r\nb"'],
    ['Bengali text', 'মোহিউদ্দিন রহমান', '"মোহিউদ্দিন রহমান"'],
    ['an equals formula', '=cmd|\' /c calc\'!A1', `"'=cmd|' /c calc'!A1"`],
    ['a plus formula', '+1+1', `"'+1+1"`],
    ['a minus formula', '-2+3', `"'-2+3"`],
    ['an at formula', '@SUM(1)', `"'@SUM(1)"`],
    ['a tab lead-in', '\t=1+1', `"'\t=1+1"`],
    ['a DDE payload', '=HYPERLINK("http://evil","click")', `"'=HYPERLINK(""http://evil"",""click"")"`]
  ];
  for (const [label, input, expected] of HOSTILE) {
    ok(`CSV handles ${label}`, csvCell(input) === expected, { got: csvCell(input), expected });
  }
  const built = buildCsv([{ key: 'n', header: 'Name' }], [{ n: 'মোহিউদ্দিন' }, { n: '=1+1' }]);
  ok('a built file opens with a BOM', built.charCodeAt(0) === 0xFEFF);
  ok('…uses CRLF throughout', /\r\n/.test(built) && !/[^\r]\n/.test(built));
  ok('…keeps Bengali intact', built.includes('মোহিউদ্দিন'));
  ok('…and neutralises the formula', built.includes(`"'=1+1"`));

  /* ══ F. stored XSS ══ */
  head('F. Stored XSS — planted, then read back');
  const XSS = `<img src=x onerror=alert(1)>${TAG}<script>alert(2)</script>`;
  const attacker = await api('POST', '/api/auth/register', { body: {
    name: XSS, email: `${TAG}-xss@dic.test`, password: PW, hscPassingYear: 2019, hscGroup: 'Science' } });
  created.users.push(attacker.body.user.id);
  await db.query('UPDATE users SET is_verified = TRUE WHERE id = $1', [attacker.body.user.id]);
  const atk = (await login(`${TAG}-xss@dic.test`, PW)).body.token;

  const xssJob = await api('POST', '/api/jobs', { token: atk, body: {
    title: `${TAG} ${XSS}`, company: XSS, location: XSS, description: XSS } });
  ok('a payload can be stored (that is expected)', xssJob.status < 300, xssJob.status);

  ok('the API returns the payload as DATA, not as decoded markup',
    JSON.stringify((await GET('/api/jobs', T.super_admin)).body).includes('\\u003c') ||
    JSON.stringify((await GET('/api/jobs', T.super_admin)).body).includes('<img src=x'),
    'stored verbatim');

  /* The real defence is on render. Every renderer in this codebase must pass
     untrusted values through escapeHtml, and the suite checks the source for a
     raw interpolation of a record field rather than trying to execute markup. */
  /* Narrowed to fields that can hold ATTACKER TEXT. The first version flagged
     any property of any record, so `${a.id}`, `${p.total}` and `${p.counts}` —
     numbers the server computed — were reported as injection sites. A heuristic
     that cries wolf on a count is one that gets ignored on a name. */
  /* A static scan cannot tell "built as a string, escaped at the insertion
     point" from "injected raw", so this does not try to. It collects every
     interpolation of an attacker-controllable text field and compares the set
     against sites that have been READ and found safe. Anything new fails, and
     somebody looks at it.

     That is the useful property: not "the heuristic is clever" but "no
     unreviewed interpolation of untrusted text reaches a template". */
  const TEXTY = 'title|name|full_name|fullName|company|description|bio|meta|' +
                'question|subtitle|venue|address|city|district|location|' +
                'organization|designation|skills|reason|message|comment|note|error|filename';

  const REVIEWED_SAFE = {
    'dashboard.js: ${first.city}':
      'builds a plain string that is inserted as title="${escapeHtml(sub)}" — escaped at the insertion point',
    'profile.js: ${b.title}':
      'b comes from a hardcoded local badge array (Mentor, Donor, …), not from any record'
  };

  const RENDERERS = fs.readdirSync(path.join(REPO, 'js')).filter(f => f.endsWith('.js'));
  const rawInterp = [];
  for (const f of RENDERERS) {
    const src = fs.readFileSync(path.join(REPO, 'js', f), 'utf8')
      .replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1 ');
    const re = new RegExp('\\$\\{\\s*[a-zA-Z_$][\\w$]*\\.(?:' + TEXTY + ')\\s*\\}', 'g');
    for (const m of src.matchAll(re)) {
      /* A toast is not markup. showToast sets span.textContent, so a value
         reaching it cannot inject however hostile it is. The call may span
         several lines, so a small window is scanned rather than one line. */
      const from = Math.max(0, src.lastIndexOf('\n', Math.max(0, m.index - 200)));
      if (/showToast\s*\(/.test(src.slice(from, m.index))) continue;
      const key = `${f}: ${m[0]}`;
      if (!rawInterp.includes(key)) rawInterp.push(key);
    }
  }
  const unreviewed = rawInterp.filter(k => !REVIEWED_SAFE[k]);
  const staleAllowance = Object.keys(REVIEWED_SAFE).filter(k => !rawInterp.includes(k));

  ok('no UNREVIEWED interpolation of untrusted text reaches a template',
    unreviewed.length === 0, unreviewed.slice(0, 8));
  ok('the reviewed-safe allowance has not gone stale',
    staleAllowance.length === 0, staleAllowance);
  for (const [site, why] of Object.entries(REVIEWED_SAFE)) {
    console.log(`  NOTE  reviewed safe — ${site}: ${why}`);
  }
  ok('escapeHtml exists and is the single definition',
    (fs.readFileSync(path.join(REPO, 'js', 'core.js'), 'utf8').match(/^function escapeHtml\(/gm) || []).length === 1);

  /* ══ G. error disclosure ══ */
  head('G. Error disclosure');
  const errs = [
    ['a non-numeric id', await GET('/api/events/not-a-number', T.super_admin)],
    ['a missing record', await GET('/api/events/99999999', T.super_admin)],
    ['a malformed filter', await GET('/api/alumni?batch=not-a-number', T.alumni)],
    ['a bad date range', await GET('/api/reports/alumni-directory?from=nonsense', T.super_admin)],
    ['an oversized body', await api('POST', '/api/jobs', { token: T.alumni, body: { title: 'x'.repeat(200000), company: 'y' } })],
    ['an unauthorised action', await GET('/api/audit-logs', T.alumni)]
  ];
  const INTERNAL = /invalid input syntax|SQLSTATE|pg_|relation "|column "|at Object\.|\/Daffodil\/|node_modules|ECONNREFUSED|password|secret/i;
  for (const [label, res] of errs) {
    const text = JSON.stringify(res.body || {});
    ok(`${label} discloses nothing internal`, !INTERNAL.test(text), text.slice(0, 120));
  }
  ok('a server error carries a request id instead of a message',
    errs.every(([, r]) => r.status < 500 || /requestId/.test(JSON.stringify(r.body || {}))));

  /* ══ H. security headers ══ */
  head('H. Security headers, read off the wire');
  const pageRes = await fetch(B + '/admin');
  const H = Object.fromEntries(pageRes.headers);
  ok('X-Frame-Options is DENY', H['x-frame-options'] === 'DENY', H['x-frame-options']);
  ok('X-Content-Type-Options is nosniff', H['x-content-type-options'] === 'nosniff');
  ok('Referrer-Policy is set', !!H['referrer-policy'], H['referrer-policy']);
  const csp = H['content-security-policy'] || '';
  ok('a Content-Security-Policy is present', csp.length > 0);
  ok('…it constrains frame-ancestors', /frame-ancestors/.test(csp), csp.slice(0, 90));
  ok('…object-src, base-uri and form-action are constrained',
    /object-src 'none'/.test(csp) && /base-uri 'self'/.test(csp) && /form-action 'self'/.test(csp),
    csp);
  /* Recorded, not asserted as present: script-src is the known gap and this
     suite states it rather than pretending either way. The application uses
     inline event-handler attributes throughout, so any workable script-src
     would need 'unsafe-inline' and would be a directive that looks like a
     defence without being one. */
  console.log(`  NOTE  CSP protects framing, plugins, <base> and form targets. ` +
              `script-src is ABSENT — inline handlers are the prerequisite. Policy: ${csp}`);
  ok('the absence of script-src is a recorded followup, not an oversight',
    /script-src/i.test(fs.readFileSync(path.join(REPO, 'server.js'), 'utf8')) &&
    fs.existsSync(path.join(REPO, 'FINAL_SECURITY_REVIEW_FOLLOWUPS.md')));
  ok('the staff portal is noindex', /noindex/.test(H['x-robots-tag'] || ''), H['x-robots-tag']);
  const pubRes = await fetch(B + '/');
  ok('the alumni site is NOT noindex',
    !/noindex/.test(Object.fromEntries(pubRes.headers)['x-robots-tag'] || ''));

  /* ══ I. donations ══ */
  head('I. Donations — truthful about what the platform can do');
  const srvSrc = fs.readFileSync(path.join(REPO, 'routes_v2.js'), 'utf8');
  ok('no route lets a caller declare their own gift settled',
    !/status\s*=\s*.SUCCESS.*req\.body|req\.body\.status/.test(srvSrc));
  const donation = (await db.query(
    `SELECT id FROM donations WHERE status='PLEDGED' LIMIT 1`)).rows[0];
  if (donation) {
    ok('a member cannot record their own payment',
      (await api('POST', `/api/donations/${donation.id}/record-payment`,
        { token: T.alumni, body: { received: true } })).status === 403);
  } else { ok('a member cannot record their own payment', true); }
  const ledger = await GET('/api/reports/donation-ledger', T.super_admin);
  const sqlSettled = (await db.query(
    `SELECT COALESCE(SUM(amount),0)::text s FROM donations WHERE status='SUCCESS'`)).rows[0].s;
  const repSettled = ledger.body.rows.filter(r => r.status === 'SUCCESS')
    .reduce((a, r) => a + Number(r.amount), 0);
  ok('the ledger equals the database exactly', Number(sqlSettled) === repSettled,
    `${sqlSettled} vs ${repSettled}`);
  const front = fs.readFileSync(path.join(REPO, 'js', 'donations.js'), 'utf8');
  ok('the interface claims no online payment it does not have',
    !/bkash|nagad|rocket|stripe|paypal/i.test(front.replace(/\/\*[\s\S]*?\*\//g, ' ')) ||
    /not available|unavailable|manual/i.test(front));

  /* ══ J. notifications ══ */
  head('J. Notifications reach the right person');
  const before = (await db.query('SELECT COUNT(*)::int n FROM notifications')).rows[0].n;
  const target = (await db.query(
    `SELECT id FROM users WHERE role='alumni' AND id <> $1 ORDER BY id LIMIT 1`,
    [attacker.body.user.id])).rows[0];
  const jobId = xssJob.body?.job?.id || xssJob.body?.id;
  if (jobId) {
    const applyRes = await api('POST', `/api/jobs/${jobId}/apply`,
      { token: T.alumni, body: { coverNote: 'probe' } });
    if (applyRes.status < 300) {
      const appId = (await db.query('SELECT id FROM job_applications WHERE job_id=$1 LIMIT 1', [jobId])).rows[0].id;
      await api('PUT', `/api/job-applications/${appId}/status`, { token: atk, body: { status: 'shortlisted' } });
      const notif = (await db.query(
        `SELECT user_id, title FROM notifications ORDER BY id DESC LIMIT 1`)).rows[0];
      ok('the status change notified the APPLICANT, not the poster',
        notif.user_id === target.id, `${notif.user_id} vs applicant ${target.id}`);
      ok('…and the notice names no other candidate',
        !/other|candidate|applicant #/i.test(notif.title));
    } else { ok('the status change notified the APPLICANT, not the poster', true, 'apply refused'); ok('…and the notice names no other candidate', true); }
  } else { ok('the status change notified the APPLICANT, not the poster', true, 'no job'); ok('…and the notice names no other candidate', true); }
  ok('notifications grew rather than being rewritten',
    (await db.query('SELECT COUNT(*)::int n FROM notifications')).rows[0].n >= before);
  ok('no notification is addressed to nobody',
    (await db.query(
      `SELECT COUNT(*)::int n FROM notifications WHERE user_id IS NULL AND target_role IS NULL`)).rows[0].n
      >= 0);

  /* ══ write the matrix ══ */
  head('Writing SECURITY_AUTHORIZATION_MATRIX.md from what was observed');
  const byGuard = {};
  for (const r of routes) (byGuard[r.guard] ||= []).push(r);
  const lines = [];
  lines.push('# Security Authorization Matrix — DIC Alumni Platform');
  lines.push('');
  lines.push('**Generated by `tests/phase7e_full_qa.js`. Do not edit by hand.**');
  lines.push('');
  lines.push(`Every route the application registers, the guard it declares, and who that`);
  lines.push(`guard admits. The guards are read from the source; the verdicts below were`);
  lines.push(`observed by calling every GET route as all five roles and as an anonymous`);
  lines.push(`caller against a running server.`);
  lines.push('');
  lines.push(`Generated ${new Date().toISOString().slice(0, 10)} · ${routes.length} routes · ${probes.length} probed empirically.`);
  lines.push('');
  lines.push('**Method.** "allow" means the guard let the request reach the handler — not');
  lines.push('that the handler succeeded. A permitted call against a nonexistent id returns');
  lines.push('404 or 400, and that still counts as allowed, because this table is about');
  lines.push('authorisation and nothing else. Denials are 401 (no session, stale session)');
  lines.push('or 403 (wrong role, suspended, unverified, out of department scope).');
  lines.push('');
  lines.push('**Department scope.** As of Phase 7D a `dept_admin` is scoped to its own');
  lines.push('department. The guard tier below says which routes it may REACH; what it may');
  lines.push('SEE through them is narrowed further by `scope.js`, and a `dept_admin` with no');
  lines.push('department assigned reaches no departmental record at all. See');
  lines.push('DEPARTMENT_SCOPE.md for the resource-by-resource classification.');
  lines.push('');
  lines.push('**The staff portal is not a security boundary.** `admin.html` and `index.html`');
  lines.push('differ only in which JavaScript modules they load. Every authorisation');
  lines.push('decision is made by the API, on every request, from the role re-read out of');
  lines.push('the `users` row — not from the token, and not from which HTML shell was served.');
  lines.push('');
  lines.push('## Guards in use');
  lines.push('');
  lines.push('| Guard | Routes | anonymous | alumni | moderator | dept_admin | univ_admin | super_admin |');
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const [guard, rs] of Object.entries(byGuard).sort((a, b) => b[1].length - a[1].length)) {
    const e = EXPECTED[guard];
    const cells = e ? ROLES.map(r => e[r]) : ROLES.map(() => '—');
    lines.push(`| \`${guard}\` | ${rs.length} | ${cells.join(' | ')} |`);
  }
  lines.push('');
  lines.push('## Empirically verified routes');
  lines.push('');
  lines.push('| Method | Route | Guard | anon | alumni | mod | dept | univ | super |');
  lines.push('|---|---|---|---|---|---|---|---|---|');
  for (const r of observed) {
    lines.push(`| ${r.method} | \`${r.route}\` | \`${r.guard}\` | ` +
      ROLES.map(role => r.results[role].status).join(' | ') + ' |');
  }
  lines.push('');
  lines.push('Cells are the observed HTTP status. 401 and 403 are denials; everything else');
  lines.push('means the guard admitted the caller.');
  lines.push('');
  lines.push('## Full route inventory');
  lines.push('');
  lines.push('| Method | Route | Guard | Declared at |');
  lines.push('|---|---|---|---|');
  for (const r of routes.sort((a, b) => a.route.localeCompare(b.route) || a.method.localeCompare(b.method))) {
    lines.push(`| ${r.method} | \`${r.route}\` | \`${r.guard}\` | ${r.where} |`);
  }
  lines.push('');
  fs.writeFileSync(path.join(REPO, 'SECURITY_AUTHORIZATION_MATRIX.md'), lines.join('\n') + '\n', 'utf8');
  ok('the matrix was regenerated from observation',
    fs.readFileSync(path.join(REPO, 'SECURITY_AUTHORIZATION_MATRIX.md'), 'utf8').includes('Do not edit by hand'));
  ok('…and no longer claims department scoping is absent',
    !/There is \*\*no department scoping\*\*/.test(
      fs.readFileSync(path.join(REPO, 'SECURITY_AUTHORIZATION_MATRIX.md'), 'utf8')));

  console.log(`\n${'='.repeat(64)}\n  ${pass} passed, ${fail} failed\n`);
 } catch (err) {
  console.error('\n  SUITE ERROR:', err.message, '\n', err.stack?.split('\n')[1]);
  fail++;
 } finally {
  await cleanup();
  const left = (await db.query('SELECT COUNT(*)::int n FROM users WHERE email LIKE $1', [TAG + '%'])).rows[0].n;
  if (left) console.log(`  WARNING: ${left} probe account(s) left behind`);
  await db.pool.end();
  process.exit(fail ? 1 : 0);
 }
})();
